# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        # Replace 'your-dockerhub-username/todo-app:latest' with your actual image name
        image: your-dockerhub-username/todo-app:latest
        ports:
        - containerPort: 8000 # The port the container will listen on
        env:
        - name: PORT
          value: "8000"
