apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo
        image: todo-app:latest
        env:
        - name: PORT
          value: "8000"
        imagePullPolicy: Never
      restartPolicy: Always
---
apiVersion: v1
kind: Namespace
metadata:
  name: todo